name: Publish latest production

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: get-version
        name: Get tag
        run: echo tag=`echo ${{ github.ref }} | awk '{ sub(/^refs\/tags\//, ""); print; }'` > $GITHUB_OUTPUT
      - name: Download tarball
        run: gh release download ${{ steps.get-version.outputs.tag }} --dir ./release
        env:
          GH_TOKEN: ${{ github.token }}
      - run: ls -la ./release
  #     - run: npm publish --tag main `ls *.tgz`
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
