name: Publish latest production

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download tarball
        run: gh release download ${{ github.ref }}
        env:
          GH_TOKEN: ${{ github.token }}
      - run: ls -la
  #     - run: npm publish --tag main `ls *.tgz`
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
